"""Generate pinned, runtime-independent Unicode matching data for Dart.

No application imports, credentials, or network. Regenerate with the locked
Python/RapidFuzz toolchain, then run Dart safety parity tests. Not app runtime.
"""
from pathlib import Path
import unicodedata

import rapidfuzz
from rapidfuzz import utils


def ranges(values):
    result = []
    for value in values:
        if result and result[-1][1] + 1 == value:
            result[-1][1] = value
        else:
            result.append([value, value])
    return result


def main():
    words, processed, folds = [], [], {}
    for code in range(0x110000):
        char = chr(code)
        if char.isalnum() or char == "_":
            words.append(code)
        value = utils.default_process(char)
        if value:
            assert len(value) == 1
            delta = ord(value) - code
            if processed and processed[-1][1] + 1 == code and processed[-1][2] == delta:
                processed[-1][1] = code
            else:
                processed.append([code, code, delta])
        if char.casefold() != char:
            folds[code] = char.casefold()

    lines = [
        "// GENERATED by tools/export_unicode_tables.py; do not edit.",
        f"// Python Unicode {unicodedata.unidata_version}; RapidFuzz {rapidfuzz.__version__}.",
        "// Pinned data avoids host/VM Unicode-version differences in price evidence.",
        "const pythonWordRanges = <int>[",
        *[f"  {value}," for row in ranges(words) for value in row],
        "];", "", "// start, end, lowercase delta; omitted codepoints become ONE space.",
        "const rapidFuzzProcessRanges = <int>[",
        *[f"  {value}," for row in processed for value in row],
        "];", "", "const pythonCaseFolds = <int, String>{",
        *[f"  {code}: '" + "".join(f"\\u{{{ord(c):x}}}" for c in value) + "'," for code, value in folds.items()],
        "};", "",
    ]
    path = Path(__file__).resolve().parent.parent / "deal_finder_app/lib/src/domain/matching/unicode_tables.g.dart"
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated Unicode word ranges={len(ranges(words))}, processor ranges={len(processed)}, case folds={len(folds)}")


if __name__ == "__main__":
    main()
